site_name: Bou CSE Resources
site_url: https://boucseresources.github.io/all/
# nav:
#   - Home: index.md
#   - Resources:
#       - Overview: bou-resources/index.md # This fixes the `/bou-resources/` link
#       - Tags: bou-resources/Tags/index.md
#   - CSE Topics:
#       - All: bou-resources/bou-cse/

theme:
  name: material
  font:
    text: Noto Serif Bengali
    code: Roboto Mono
  logo: assets/logo-bou.png
  favicon: assets/logo-bou.png
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.sections
    - navigation.indexes
    - toc.follow
    # - navigation.expand
    - navigation.top
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: light green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: deep orange
plugins:
  - search
  - glightbox
  - obsidian-bridge
  - awesome-pages

# git branch -M main

# git push -u origin main

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rakibulhashanrabbi/
  analytics:
    provider: google
    property: G-L5PLKJC0BE
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  meta:
    - name: google-site-verification
      content: 2DzSK5YqtUmF6BuC8wVWanf-j8tYFIEKnuQPi6Vkq0o
    - name: description
      content: "Free CSE study materials for Bangladesh Open University students."
    - name: keywords
      content: "bou admission, bou cse admission, bou cse admission circular, bou cse, bou cse resources, bangladesh open university, bou sst"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - markdown.extensions.nl2br
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

    # extra:
    #   social:
    #     - icon: simple/youtube
    #       link: https://youtube.com/@james-willett
    #     - icon: simple/linkedin
    #       link: https://linkedin.com/in/willettjames

extra_javascript:
  - meta-inject.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
copyright: Copyright &copy; 2025 Rakibul Hashan
