name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-glightbox mkdocs-obsidian-bridge mkdocs-get-deps mkdocs-awesome-pages-plugin mkdocs-mcq mkdocs-toggle-sidebar-plugin

      # Clean cache before build to prevent FileNotFoundError bugs
      - name: Purge MkDocs Cache
        run: rm -rf .cache

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
      - name: Clear broken privacy cache
        run: rm -rf .cache/plugin/privacy